# Generated by Django 4.2.5 on 2023-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auditlog_person_id_delete_historicalperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
