# Generated by Django 4.2.5 on 2023-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_auditlog_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
