# Generated by Django 4.2.5 on 2023-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_auditlog_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
