# Generated by Django 4.2.5 on 2023-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_person_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.CharField(default='Nothing', max_length=1000),
            preserve_default=False,
        ),
    ]
